### ISSUE TITLE
Colored target in same position for any given seed.

### ISSUE THREAD

**Issue by Aycorn** [gjeuken/telewave#1]
As any example on seed 0, the colored target is set to 78%:

![image](https://user-images.githubusercontent.com/30588784/80271560-8ccbb200-8704-11ea-92b7-c65a79914294.png)

Reloading the game or reloading the seed will also center the colored target on 78%.

Each seed has a different target center, however the answer to a specific spectrum can often be remembered if you come across the same seed twice.

Looks to be getting the first random number for a given seed rather than selecting from the available random numbers for a seed.

**Comment by gjeuken** [comment]
Hi,
This is done by design.
The idea is that by having unique boards for each seed, the person who peeks where the target is can do so on his own computer or phone, using the same seed as the one being shared on screen.
This eliminates the need to ask other people to close their eyes, etc. 
It takes away some of the organizational overhead in playing and enjoying the game, imho.

**Comment by gjeuken** [comment]
I've added an instructions page to make this clearer.

**Comment by Aycorn** [comment]
Thanks @gjeuken makes sense :) Loving this game at the moment and really appreciate the work you've done!
